name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 0.3.0+2
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  cloud_firestore: ^0.16.0
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
